import { taedUrl, vendorEyeUrl } from './external-resources'

export type AiLibraryArticle = {
  number: number
  slug: string
  title: string
  type: string
  cluster: string
  topics: string[]
  related: number[]
  product?: 'taed' | 'vendoreye' | 'both'
  download?: string
}

const rows: Array<Omit<AiLibraryArticle, 'number'>> = [
  { slug:'ai-in-healthcare-uae-practical-guide', title:'AI in Healthcare in the UAE: A Practical Guide for Providers', type:'Pillar guide', cluster:'Healthcare', topics:['clinical and administrative boundaries','imaging and documentation','scheduling, claims, and patient communication','privacy, oversight, and deployment planning'], related:[2,31,33,41,46], download:'Healthcare AI Opportunity and Risk Matrix' },
  { slug:'applied-ai-use-cases-uae-hospitals-clinics', title:'Ten Applied AI Use Cases for UAE Hospitals and Clinics', type:'Applied-AI guide', cluster:'Healthcare', topics:['appointment and call handling','medical-document extraction','claims and coding support','multilingual patient information and maintenance'], related:[1,3,42,44], product:'taed', download:'AI Use-Case Prioritization Matrix' },
  { slug:'healthcare-ai-readiness-checklist', title:'Healthcare AI Readiness Checklist', type:'Checklist', cluster:'Healthcare', topics:['data sensitivity and clinical safety','model validation and integrations','patient consent and multilingual testing','downtime procedures and accountable ownership'], related:[1,2,41,46,49], download:'Enterprise AI Readiness Audit Workbook' },
  { slug:'ai-in-procurement-decision-intelligence', title:'AI in Procurement: From Administrative Automation to Decision Intelligence', type:'Pillar guide', cluster:'Procurement', topics:['supplier discovery and onboarding','evidence extraction and verification','sourcing and contract intelligence','spend, risk, and human-controlled decisions'], related:[5,6,32,37,48], product:'both', download:'AI Vendor RFP and Evaluation Template' },
  { slug:'applied-ai-use-cases-uae-procurement', title:'Twenty Applied AI Use Cases for UAE Procurement Teams', type:'Applied-AI guide', cluster:'Procurement', topics:['supplier intake and duplicate detection','qualification and questionnaire analysis','bid comparison and price variance','renewals, risk alerts, and invoice exceptions'], related:[4,6,42,45,48], product:'vendoreye', download:'AI Use-Case Prioritization Matrix' },
  { slug:'procurement-ai-readiness-audit', title:'Procurement AI Readiness Audit: Can Your Organization Automate Safely?', type:'Audit guide', cluster:'Procurement', topics:['vendor-master and evidence quality','ERP and approval integration','segregation of duties and fraud controls','audit history and decision boundaries'], related:[4,5,41,45,48], product:'vendoreye', download:'Procurement Transformation Readiness Workbook' },
  { slug:'ai-in-landscaping-uae', title:'AI in Landscaping: Smarter Irrigation, Maintenance, and Field Operations', type:'Pillar guide', cluster:'Landscaping', topics:['plant-health computer vision','weather-aware irrigation and leakage','routing and workforce dispatch','asset monitoring, quotations, and reporting'], related:[8,9,35,38,44], product:'taed' },
  { slug:'computer-vision-plant-health-landscape-inspection', title:'Computer Vision for Plant Health and Landscape Inspection', type:'Technical guide', cluster:'Landscaping', topics:['image capture and species recognition','disease, stress, and irrigation symptoms','geolocation and seasonal variation','human verification and field testing'], related:[7,9,35,38,44], product:'taed', download:'Media-AI Readiness Checklist' },
  { slug:'landscaping-ai-readiness-checklist', title:'Landscaping AI Readiness Checklist', type:'Checklist', cluster:'Landscaping', topics:['assets, telemetry, and work orders','images, maps, and weather feeds','field applications and connectivity','customer reporting and water baselines'], related:[7,8,41,43,44], download:'Media-AI Readiness Checklist' },
  { slug:'ai-in-telecom-applied-use-cases', title:'AI in Telecom: Applied Use Cases Beyond Customer-Service Chatbots', type:'Pillar guide', cluster:'Telecom', topics:['network anomalies and capacity','predictive maintenance and field service','fraud, churn, and contact centres','tower inspection, documents, and procurement'], related:[11,12,34,36,47] },
  { slug:'multimodal-ai-telecom-field-inspection', title:'Using Multimodal AI for Telecom Field Inspection', type:'Applied-AI guide', cluster:'Telecom', topics:['tower and equipment imagery','technician notes, manuals, and telemetry','defect evidence and offline operation','safety, validation, and escalation'], related:[10,12,35,38,44], product:'taed', download:'Media-AI Readiness Checklist' },
  { slug:'telecom-ai-readiness-audit', title:'Telecom AI Readiness Audit', type:'Audit guide', cluster:'Telecom', topics:['network data and alarm quality','asset hierarchy and OSS/BSS','privacy, recordings, and bilingual testing','latency, monitoring, and escalation'], related:[10,11,41,46,47], download:'Enterprise AI Readiness Audit Workbook' },
  { slug:'ai-in-construction-uae-implementation-guide', title:'AI in Construction: A UAE Contractor’s Implementation Guide', type:'Pillar guide', cluster:'Construction', topics:['site safety and progress','document control and quantity checks','tendering, procurement, and delay risk','claims, equipment, and reporting'], related:[14,15,31,39,45], product:'both' },
  { slug:'computer-vision-construction-progress-safety', title:'Computer Vision for Construction Progress and Safety', type:'Applied-AI guide', cluster:'Construction', topics:['PPE and restricted-area detection','activity and progress recognition','planned-versus-actual evidence','privacy, false alarms, and field testing'], related:[13,15,35,38,44], product:'taed', download:'Media-AI Readiness Checklist' },
  { slug:'construction-ai-readiness-checklist', title:'Construction AI Readiness Checklist', type:'Checklist', cluster:'Construction', topics:['BIM and drawing versions','camera coverage and subcontractor data','daily reports and procurement systems','connectivity, policies, and evaluation sets'], related:[13,14,41,43,49], download:'Production Go-Live Checklist' },
  { slug:'ai-in-uae-real-estate', title:'AI in UAE Real Estate: From Lead Qualification to Property Operations', type:'Pillar guide', cluster:'Real Estate', topics:['lead handling and property search','multilingual communication and valuation','documents and property inspection','tenant services and portfolio operations'], related:[17,18,33,35,43] },
  { slug:'multimodal-ai-property-inspection-handover', title:'Multimodal AI for Property Inspection and Handover', type:'Applied-AI guide', cluster:'Real Estate', topics:['images, video, and floor plans','snagging and defect classification','severity, duplicates, and evidence quality','structured reports and contractor follow-up'], related:[16,18,35,38,44], product:'taed', download:'Media-AI Readiness Checklist' },
  { slug:'real-estate-ai-readiness-checklist', title:'Real-Estate AI Readiness Checklist', type:'Checklist', cluster:'Real Estate', topics:['property-master and listing rights','images, leases, and maintenance','CRM, consent, and pricing controls','multilingual content and approvals'], related:[16,17,41,43,46], download:'Data Readiness Workbook' },
  { slug:'ai-in-uae-logistics', title:'AI in UAE Logistics: Warehouses, Fleets, Ports, and Last-Mile Delivery', type:'Pillar guide', cluster:'Logistics', topics:['demand, routes, and warehouse vision','shipment documents and ETA prediction','damage and fleet maintenance','customs and exception management'], related:[20,21,34,38,49], product:'taed' },
  { slug:'document-image-ai-freight-operations', title:'Document and Image AI for Freight Operations', type:'Applied-AI guide', cluster:'Logistics', topics:['bills of lading and manifests','delivery evidence and container imagery','damage, invoices, and exceptions','confidence and human confirmation'], related:[19,21,35,38,44], product:'taed', download:'Media-AI Readiness Checklist' },
  { slug:'logistics-ai-readiness-audit', title:'Logistics AI Readiness Audit', type:'Audit guide', cluster:'Logistics', topics:['shipment identifiers and scan events','telematics and warehouse records','carrier integrations and exceptions','freshness, real-time systems, and fallback'], related:[19,20,41,43,49], download:'Enterprise AI Readiness Audit Workbook' },
  { slug:'ai-in-uae-hospitality', title:'AI in UAE Hospitality: Better Service Without Removing the Human Experience', type:'Pillar guide', cluster:'Hospitality', topics:['reservations and multilingual voice','reviews, demand, and personalization','housekeeping and maintenance','documents, procurement, and service recovery'], related:[23,24,36,40,50] },
  { slug:'multilingual-voice-ai-hotels-tourism', title:'Multilingual Voice AI for Hotels and Tourism', type:'Applied-AI guide', cluster:'Hospitality', topics:['Arabic-English code-switching','reservations, directions, and requests','interruptions, identity, and escalation','cultural nuance and sensitive complaints'], related:[22,24,36,47,49], download:'Multilingual AI Test Pack' },
  { slug:'hospitality-ai-readiness-checklist', title:'Hospitality AI Readiness Checklist', type:'Checklist', cluster:'Hospitality', topics:['PMS, CRM, and service catalogue','consent and language coverage','integration reliability and brand voice','escalation and seasonal testing'], related:[22,23,41,46,47], download:'Multilingual AI Test Pack' },
  { slug:'ai-in-uae-retail', title:'AI in UAE Retail: Applied Intelligence across Stores and E-commerce', type:'Pillar guide', cluster:'Retail', topics:['search, recommendations, and demand','pricing controls and shelf intelligence','loss prevention and catalog enrichment','support, returns, and suppliers'], related:[26,27,35,37,43] },
  { slug:'visual-ai-retail-shelves-products-returns', title:'Visual AI for Retail Shelves, Products, and Returns', type:'Applied-AI guide', cluster:'Retail', topics:['stock and planogram detection','damage and product recognition','return-condition assessment','privacy, cameras, and packaging change'], related:[25,27,35,38,44], product:'taed', download:'Media-AI Readiness Checklist' },
  { slug:'retail-ai-readiness-checklist', title:'Retail AI Readiness Checklist', type:'Checklist', cluster:'Retail', topics:['SKU and inventory quality','transactions and product imagery','store variation and consent','merchandising, pricing, and experiments'], related:[25,26,41,42,43], download:'Data Readiness Workbook' },
  { slug:'ai-in-uae-financial-services', title:'AI in UAE Financial Services: High-Value Applications and Hard Boundaries', type:'Pillar guide', cluster:'Financial Services', topics:['documents and fraud analysis','service and collections support','underwriting and compliance operations','employee copilots and strict oversight'], related:[29,30,33,39,47] },
  { slug:'multimodal-ai-insurance-claims-damage', title:'Multimodal AI for Insurance Claims and Damage Assessment', type:'Applied-AI guide', cluster:'Financial Services', topics:['claim documents and damage imagery','fraud indicators and severity','missing evidence and adjuster review','auditability and disputed outcomes'], related:[28,30,35,38,44], product:'taed', download:'Media-AI Readiness Checklist' },
  { slug:'financial-services-ai-readiness-audit', title:'Financial-Services AI Readiness Audit', type:'Audit guide', cluster:'Financial Services', topics:['classification and model validation','explainability and segregation of duties','limits, fraud, and audit records','third parties, incidents, and review'], related:[28,29,41,45,46], download:'Enterprise AI Readiness Audit Workbook' },
  { slug:'applied-ai-versus-demonstrations', title:'Applied AI versus AI Demonstrations: What Creates Enterprise Value?', type:'Foundational guide', cluster:'Fundamentals', topics:['workflow integration and ownership','data and evaluation','operations and measurable outcomes','durable value beyond model fluency'], related:[33,38,39,41,49] },
  { slug:'what-ai-should-automate', title:'What AI Should Automate—and What Humans Should Continue to Decide', type:'Governance guide', cluster:'Fundamentals', topics:['reversibility and consequence','uncertainty and accountability','transaction value and legal effect','exception frequency and risk tiers'], related:[31,37,41,45,49], product:'vendoreye', download:'Human-versus-AI Decision Matrix' },
  { slug:'enterprise-ai-stack-explained', title:'The Enterprise AI Stack Explained in Plain Language', type:'Foundational guide', cluster:'Fundamentals', topics:['data, models, prompts, and RAG','tools, agents, and APIs','identity, applications, and evaluation','monitoring and governance'], related:[31,34,35,38,43], product:'taed', download:'Data Readiness Workbook' },
  { slug:'rag-fine-tuning-agents-automation', title:'RAG, Fine-Tuning, Agents, or Traditional Automation?', type:'Decision guide', cluster:'Fundamentals', topics:['problem-method fit','required data and determinism','cost and maintenance','selection errors and decision paths'], related:[33,38,39,42,49], download:'AI Use-Case Prioritization Matrix' },
  { slug:'multimodal-ai-images-audio-video-documents', title:'Multimodal AI: Combining Images, Audio, Video, Documents, and Data', type:'Foundational guide', cluster:'Fundamentals', topics:['multimodal inputs and synchronization','schemas and evidence alignment','latency, storage, and privacy','field evaluation and operations'], related:[33,38,43,44,49], product:'taed', download:'Media-AI Readiness Checklist' },
  { slug:'voice-agents-reality-check', title:'Voice Agents: What Works, What Remains Difficult, and What May Be Short-Lived', type:'Critical analysis', cluster:'Fundamentals', topics:['economics and commoditization','latency, interruptions, and dialects','tool reliability and identity','escalation, unit economics, and durable assets'], related:[31,35,39,47,49], download:'Multilingual AI Test Pack' },
  { slug:'evidence-backed-ai-versus-black-box', title:'Evidence-Backed AI versus Black-Box AI', type:'Governance guide', cluster:'Fundamentals', topics:['citations and source evidence','confidence and audit trails','corrections and authority','review in regulated workflows'], related:[32,38,41,45,48], product:'vendoreye', download:'Human-versus-AI Decision Matrix' },
  { slug:'apis-schemas-validation-versioning-production-ai', title:'Why APIs, Schemas, Validation, and Versioning Matter in Production AI', type:'Technical guide', cluster:'Fundamentals', topics:['prompts versus products','reusable contracts and structured outputs','validation, versioning, and monitoring','rollback and provider replacement'], related:[31,33,35,39,49], product:'taed', download:'Production Go-Live Checklist' },
  { slug:'real-cost-enterprise-ai', title:'The Real Cost of Enterprise AI', type:'Financial guide', cluster:'Fundamentals', topics:['integration and data preparation','inference, media, and storage','monitoring and human review','testing, failures, and support'], related:[31,34,38,41,50], download:'Enterprise AI TCO Calculator' },
  { slug:'building-proprietary-ai-ip', title:'Building Proprietary AI IP Without Training a Foundation Model', type:'Strategy guide', cluster:'Fundamentals', topics:['domain schemas and workflows','integrations and evaluation sets','correction data, APIs, and taxonomies','operational knowledge and distribution'], related:[31,33,38,39,50], product:'both' },
  { slug:'complete-enterprise-ai-readiness-audit', title:'The Complete Enterprise AI Readiness Audit', type:'Flagship audit', cluster:'Planning & Readiness', topics:['strategy, value, and data','technology, security, and privacy','governance, people, and integration','evaluation, operations, and finance'], related:[42,43,46,49,50], download:'Enterprise AI Readiness Audit Workbook' },
  { slug:'ai-use-case-prioritization-checklist', title:'AI Use-Case Prioritization Checklist', type:'Checklist', cluster:'Planning & Readiness', topics:['value and feasibility','data and risk','integration effort and time to value','adoption, reversibility, and ownership'], related:[31,34,39,41,50], download:'AI Use-Case Prioritization Matrix' },
  { slug:'enterprise-data-readiness-checklist-ai', title:'Enterprise Data Readiness Checklist for AI', type:'Checklist', cluster:'Planning & Readiness', topics:['ownership, quality, and lineage','permissions, freshness, and identifiers','metadata and bilingual coverage','media quality, retention, and test data'], related:[33,35,41,46,49], download:'Data Readiness Workbook' },
  { slug:'computer-vision-media-ai-readiness-checklist', title:'Computer Vision and Media-AI Readiness Checklist', type:'Checklist', cluster:'Planning & Readiness', topics:['capture conditions and labels','variation, privacy, and storage','bandwidth and edge requirements','schemas, evaluation, and field tests'], related:[35,38,41,43,49], product:'taed', download:'Media-AI Readiness Checklist' },
  { slug:'ai-vendor-evaluation-procurement-checklist', title:'AI Vendor Evaluation and Procurement Checklist', type:'Buyer’s guide', cluster:'Planning & Readiness', topics:['data use, retention, and region','subprocessors, ownership, and SLAs','evidence, portability, and incidents','exit strategy and total cost'], related:[32,37,39,41,48], product:'vendoreye', download:'AI Vendor RFP and Evaluation Template' },
  { slug:'ai-security-privacy-readiness-checklist', title:'AI Security and Privacy Readiness Checklist', type:'Checklist', cluster:'Planning & Readiness', topics:['threat modelling and prompt injection','data leakage, secrets, and identity','isolation, logging, and retention','red teaming and incident response'], related:[32,41,43,45,49], download:'Production Go-Live Checklist' },
  { slug:'multilingual-arabic-ai-readiness-checklist', title:'Multilingual and Arabic AI Readiness Checklist', type:'Checklist', cluster:'Planning & Readiness', topics:['MSA, Gulf dialects, and code-switching','transliteration and RTL interfaces','entities, numbers, and test coverage','evaluation and human escalation'], related:[23,36,41,46,49], download:'Multilingual AI Test Pack' },
  { slug:'procurement-transformation-readiness-checklist', title:'Procurement Transformation Readiness Checklist', type:'Checklist', cluster:'Planning & Readiness', topics:['vendor master and supplier evidence','approval policies and onboarding','sourcing, ERP, and fraud controls','renewals, reporting, and ownership'], related:[4,6,37,41,45], product:'vendoreye', download:'Procurement Transformation Readiness Workbook' },
  { slug:'ai-production-readiness-checklist', title:'AI Production Readiness Checklist: Before You Go Live', type:'Release checklist', cluster:'Planning & Readiness', topics:['test cases, load, and security','failure injection and rollback','monitoring, costs, and versions','human escalation, support, and incidents'], related:[38,41,44,46,50], product:'taed', download:'Production Go-Live Checklist' },
  { slug:'12-month-ai-transformation-roadmap', title:'The 12-Month AI Transformation Roadmap', type:'Executive guide', cluster:'Planning & Readiness', topics:['readiness and opportunity audit','data and governance foundations','controlled pilots and production platform','sector workflows, measurement, and IP'], related:[31,39,40,41,42], product:'both', download:'12-Month AI Transformation Roadmap' },
]

export const aiLibraryArticles: AiLibraryArticle[] = rows.map((article, index) => ({ ...article, number: index + 1 }))
export const aiLibraryClusters = [...new Set(aiLibraryArticles.map((article) => article.cluster))]
export const getAiLibraryArticle = (slug: string) => aiLibraryArticles.find((article) => article.slug === slug)
export const getAiLibraryByNumber = (number: number) => aiLibraryArticles.find((article) => article.number === number)
export const getAiLibraryRelated = (article: AiLibraryArticle) => article.related.map(getAiLibraryByNumber).filter((item): item is AiLibraryArticle => Boolean(item))

export const productContext = {
  taed: { name:'TAED', href:taedUrl, copy:'Production systems need more than a prompt. TAED provides schema definition, validation, versioning, API exposure, and monitoring for visual, audio, and video AI workflows.' },
  vendoreye: { name:'VendorEye', href:vendorEyeUrl, copy:'Procurement AI needs evidence and accountable decisions. VendorEye connects supplier intake, verification, sourcing, and continuing governance in one controlled workflow.' },
}

export const resourceSlugByName: Record<string, string> = {
  'Enterprise AI Readiness Audit Workbook':'enterprise-ai-readiness-audit-workbook',
  'AI Use-Case Prioritization Matrix':'ai-use-case-prioritization-matrix',
  'Human-versus-AI Decision Matrix':'human-versus-ai-decision-matrix',
  'Enterprise AI TCO Calculator':'enterprise-ai-tco-calculator',
  'AI Vendor RFP and Evaluation Template':'ai-vendor-rfp-evaluation-template',
  'Data Readiness Workbook':'data-readiness-workbook',
  'Media-AI Readiness Checklist':'media-ai-readiness-checklist',
  'Multilingual AI Test Pack':'multilingual-ai-test-pack',
  'Production Go-Live Checklist':'production-go-live-checklist',
  'Procurement Transformation Readiness Workbook':'enterprise-ai-readiness-audit-workbook',
  '12-Month AI Transformation Roadmap':'12-month-ai-transformation-roadmap',
  'Healthcare AI Opportunity and Risk Matrix':'ai-use-case-prioritization-matrix',
}

export const deckSlugByCluster: Record<string, string> = {
  Healthcare:'ai-in-healthcare', Procurement:'ai-in-procurement', Landscaping:'ai-in-landscaping-field-services', Telecom:'ai-in-telecom', Construction:'ai-in-construction', 'Real Estate':'ai-in-real-estate', Logistics:'ai-in-logistics', Hospitality:'ai-in-hospitality', Fundamentals:'building-proprietary-ai-ip', 'Planning & Readiness':'enterprise-ai-readiness',
}
