import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight } from 'lucide-react'
import { PageHeader } from '@/components/page-header'
import { Reveal } from '@/components/reveal'
import { partnerAudienceList } from '@/lib/partnerships'
import { pageMetadata } from '@/lib/seo'
export const metadata:Metadata=pageMetadata({title:'Partner with AI7Lab',description:'Three partnership paths connecting AI builders, enterprise demand, and technology infrastructure through governed proofs and commercial evidence.',path:'/partners',keywords:['AI partnerships UAE','AI startup enterprise partnership','technology ecosystem Middle East']})
export default function PartnersPage(){return <><PageHeader eyebrow="AI7Lab partnership network" title="Builders, enterprises, and technology providers—connected around real AI outcomes." description="AI7Lab creates the missing operating layer between promising products, enterprise demand, and the infrastructure required to prove and scale them."/><main><section className="border-b border-border"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-6 md:py-28"><div className="grid gap-6 lg:grid-cols-3">{partnerAudienceList.map((page,i)=><Reveal key={page.slug} delay={i*80}><Link href={`/partners/${page.slug}`} className="group flex h-full flex-col rounded-3xl border border-border bg-card/40 p-7 transition-all hover:-translate-y-1 hover:border-primary/30 hover:shadow-xl hover:shadow-primary/5 sm:p-8"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><page.icon className="h-6 w-6"/></div><p className="mt-8 font-mono text-xs uppercase tracking-[0.18em] text-primary">{page.eyebrow}</p><h2 className="mt-4 text-2xl font-semibold tracking-tight">{page.title}</h2><p className="mt-4 flex-1 leading-7 text-muted-foreground">{page.description}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-medium text-primary">Explore this partnership<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1"/></span></Link></Reveal>)}</div></div></section><section className="bg-[#07172b] text-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-6 md:py-20"><p className="font-mono text-xs uppercase tracking-[0.2em] text-blue-300">The shared model</p><div className="mt-6 grid gap-8 md:grid-cols-4">{[['01','Define a real workflow'],['02','Match the right capability'],['03','Prove it inside clear boundaries'],['04','Scale only when evidence supports it']].map(([n,t])=><div key={n} className="border-t border-white/15 pt-4"><span className="font-mono text-xs text-blue-300">{n}</span><p className="mt-3 text-lg font-medium">{t}</p></div>)}</div></div></section></main></>}
