import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, ExternalLink, ShieldCheck } from 'lucide-react'
import { articleDescription, articleImageAlt, editorialArticles, focusAnalysis, focusPoints, getEditorialArticle, getPillar, getPillarImage, getRelatedEditorial, primaryKeyword, shareTakeaway, sourcesForArticle, topicKeywords } from '@/lib/editorial'
import { siteUrl } from '@/lib/site'

type Props = { params: Promise<{ slug: string }> }
export function generateStaticParams() { return editorialArticles.map(({ slug }) => ({ slug })) }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const article = getEditorialArticle((await params).slug)
  if (!article) return {}
  const description = articleDescription(article)
  const path = `/insights/research/${article.slug}`
  const image = `${path}/opengraph-image`
  return {
    title: article.title, description,
    keywords: topicKeywords(article),
    alternates: { canonical: path }, authors: [{ name: 'AI7Lab Research & Product Team' }],
    openGraph: { type: 'article', locale: 'en_AE', siteName: 'AI7Lab', url: path, title: article.title, description, publishedTime: '2026-08-26', modifiedTime: '2026-08-26', section: getPillar(article).title, tags: topicKeywords(article), images: [{ url: image, width: 1200, height: 630, alt: article.title }] },
    twitter: { card: 'summary_large_image', title: article.title, description, images: [image] },
  }
}

export default async function ResearchArticlePage({ params }: Props) {
  const article = getEditorialArticle((await params).slug)
  if (!article) notFound()
  const pillar = getPillar(article)
  const points = focusPoints(article)
  const analysis = focusAnalysis(article)
  const sources = sourcesForArticle(article)
  const related = getRelatedEditorial(article)
  const description = articleDescription(article)
  const taedArticle = article.pillar === 13 || (article.pillar === 12 && article.number <= 117)
  const vendorEyeArticle = article.pillar === 14 || (article.pillar === 12 && (article.number === 118 || article.number === 119))
  const productArticle = article.pillar >= 12 && article.pillar <= 14
  const productName = taedArticle ? 'TAED' : vendorEyeArticle ? 'VendorEye' : 'TAED and VendorEye'
  const productHref = taedArticle ? 'https://taed.dev' : vendorEyeArticle ? 'https://vendoreye.ae' : '/products'
  const productAction = taedArticle ? 'Test one representative document with TAED' : vendorEyeArticle ? 'Map one complete supplier journey with VendorEye' : 'Explore AI7Lab’s product and IP approach'
  const url = `${siteUrl}/insights/research/${article.slug}`
  const schema = { '@context': 'https://schema.org', '@type': 'BlogPosting', headline: article.title, description, image: [`${siteUrl}${getPillarImage(article.pillar)}`], datePublished: '2026-08-26', dateModified: '2026-08-26', author: { '@type': 'Organization', name: 'AI7Lab' }, publisher: { '@type': 'Organization', name: 'AI7Lab', logo: { '@type': 'ImageObject', url: `${siteUrl}/ai7lab-logo.png` } }, mainEntityOfPage: url, about: [primaryKeyword(article), 'Enterprise AI in the UAE', pillar.title], inLanguage: 'en-AE' }
  const breadcrumbSchema = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl }, { '@type': 'ListItem', position: 2, name: 'Insights', item: `${siteUrl}/insights` }, { '@type': 'ListItem', position: 3, name: pillar.title, item: `${siteUrl}/insights#pillar-${article.pillar}` }, { '@type': 'ListItem', position: 4, name: article.title, item: url }] }
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema).replace(/</g, '\\u003c') }} />
    <header className="border-b border-border bg-grid pt-32 sm:pt-36 md:pt-44"><div className="mx-auto max-w-5xl px-5 pb-14 sm:px-6 md:pb-20">
      <Link href="/insights" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft className="h-4 w-4" />AI7Lab Research</Link>
      <div className="mt-10 flex flex-wrap items-center gap-3 text-sm text-muted-foreground"><span className="rounded-full bg-blue-50 px-3 py-1 font-medium text-primary">Pillar {article.pillar} · {pillar.title}</span><time dateTime="2026-08-26">26 August 2026</time><span>·</span><span className="flex items-center gap-1.5"><Clock3 className="h-4 w-4" />10 min read</span></div>
      <h1 className="mt-6 max-w-4xl text-balance text-4xl font-semibold tracking-tight sm:text-5xl md:text-6xl">{article.title}</h1>
      <p className="mt-6 max-w-3xl text-pretty text-lg leading-relaxed text-muted-foreground sm:text-xl">{description}</p>
      <p className="mt-7 font-mono text-xs uppercase tracking-[0.18em] text-primary">Research note {String(article.number).padStart(3, '0')} · UAE / GCC</p>
    </div></header>
    <main><div className="mx-auto max-w-6xl px-5 py-10 sm:px-6 md:py-16"><figure><div className="relative aspect-[3/2] overflow-hidden rounded-3xl border border-border bg-secondary shadow-2xl shadow-primary/10"><Image src={getPillarImage(article.pillar)} alt={articleImageAlt(article)} fill priority className="object-cover" sizes="(max-width: 1200px) 100vw, 1152px" /></div><figcaption className="mt-3 text-sm text-muted-foreground">AI7Lab editorial illustration: {article.imagePrompt}</figcaption></figure></div>
      <article className="mx-auto max-w-3xl px-5 pb-24 sm:px-6">
        <p className="text-xl leading-9">For UAE and GCC leaders, {article.title.toLowerCase()} is not a model-selection exercise. It is an operating-system decision: business value, data, architecture, risk, ownership, and adoption must work as one production discipline.</p>
        <section className="mt-16"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Executive brief</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">What decision-makers need to resolve</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">The useful question is not whether the technology is impressive. It is whether a team can define an acceptable outcome, measure failure, protect sensitive information, integrate the result into a real workflow, and operate it at a defensible cost. In the UAE, that assessment also needs to reflect applicable sector rules, data handling obligations, Arabic and English user journeys, procurement constraints, and the organization’s risk appetite.</p><ul className="mt-8 space-y-3">{points.map((point) => <li key={point} className="flex gap-3 rounded-xl border border-border p-4 leading-7"><CheckCircle2 className="mt-1 h-5 w-5 shrink-0 text-primary" />{point}</li>)}</ul></section>
        <section className="mt-16"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Topic analysis</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Turning the brief into operating requirements</h2><p className="mt-5 leading-7 text-muted-foreground">Each requirement below is evaluated as part of the specific decision in this article. The aim is to leave a UAE or GCC enterprise team with evidence it can request—not a list of technology claims.</p><div className="mt-8 divide-y divide-border border-y border-border">{analysis.map((item) => <section key={`${item.index}-${item.heading}`} className="py-7"><h3 className="text-xl font-semibold leading-snug">{item.heading}</h3><p className="mt-3 leading-7 text-muted-foreground">{item.analysis}</p><p className="mt-3 text-sm leading-6 text-primary">{item.proof}</p></section>)}</div></section>
        <section className="mt-16"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Reference architecture</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Design from the controlled outcome backwards</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{[['1 · Outcome contract','Define the user, decision, baseline, target, acceptable failure rate, and escalation path before choosing a model.'],['2 · Governed context','Classify data, enforce identity and permissions, retain provenance, and minimize the information exposed to each component.'],['3 · Intelligence layer','Route across models, retrieval, rules, tools, and deterministic services according to quality, latency, and cost.'],['4 · Operational control','Evaluate before release; observe quality, security, adoption, and unit economics; preserve rollback and human override.']].map(([title,copy]) => <div key={title} className="rounded-2xl border border-border bg-card p-6"><h3 className="font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></div>)}</div></section>
        <section className="mt-16"><h2 className="text-3xl font-semibold tracking-tight">Build, buy, or combine?</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Buy when the workflow is standardized and differentiation is low. Build when proprietary data, a distinctive process, deep integration, or control over quality creates durable value. Most UAE enterprises should combine the two: procure commodity infrastructure and model access, while owning the evaluation data, permission model, orchestration, integrations, and operating metrics that make the system defensible.</p><div className="mt-7 overflow-hidden rounded-2xl border border-border"><div className="grid grid-cols-3 bg-secondary px-5 py-3 text-sm font-semibold"><span>Decision</span><span>Prefer buy</span><span>Prefer build</span></div>{[['Differentiation','Low','High'],['Data sensitivity','Standard controls','Unique controls'],['Integration depth','Light','Deep'],['Switching cost','Acceptable','Must be controlled']].map((row) => <div key={row[0]} className="grid grid-cols-3 border-t border-border px-5 py-3 text-sm"><span className="font-medium">{row[0]}</span><span className="text-muted-foreground">{row[1]}</span><span className="text-muted-foreground">{row[2]}</span></div>)}</div></section>
        <section className="mt-16 rounded-3xl border border-primary/15 bg-blue-50/60 p-7 sm:p-9"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-primary" /><h2 className="text-2xl font-semibold">Security, testing, cost, and operations</h2></div><p className="mt-5 leading-7 text-muted-foreground">Treat prompts, retrieved content, model output, and tool results as untrusted data. Apply least privilege, output validation, rate and spend limits, audit trails, and adversarial tests. Maintain representative golden datasets across Arabic, English, code-switching, edge cases, and high-impact workflows. Track cost per successful outcome—not tokens alone—and make an accountable product owner responsible for quality after launch.</p></section>
        {article.pillar === 11 && <section className="mt-16"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Voice AI reality check</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Voice is cheaper. Dependable voice operations are not automatically simple.</h2><div className="mt-7 grid gap-4">{[
          ['Economic reality','Measure cost per completed and correct outcome. Include telephony, inference, monitoring, transfers, repeat calls, failed calls, support, and the operational cost of repairing mistakes.'],
          ['What remains difficult','Overlapping speech, noise, dialects, implied intent, authentication, tool failures, long calls, and graceful recovery still require explicit engineering and field evaluation.'],
          ['Expected shelf life','Speech and model components may be superseded within a platform cycle. Workflow knowledge, integrations, permissions, evaluations, and multilingual operating data should survive replacement.'],
          ['Human fallback','Transfer when identity is uncertain, a consequential action cannot be confirmed, distress or conflict appears, tools fail, policy requires judgment, or the caller asks for a person. Preserve context during the handoff.'],
          ['Replaceability','Keep the model, speech provider, telephony provider, and orchestration layer behind tested interfaces. A provider change should trigger evaluation and controlled rollout—not a workflow rewrite.'],
        ].map(([title,copy]) => <div key={title} className="rounded-2xl border border-border bg-card p-6"><h3 className="font-semibold">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{copy}</p></div>)}</div></section>}
        {productArticle && <section className="mt-16 rounded-3xl border border-border bg-card p-7 sm:p-9"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">Product relationship and alternatives</p><h2 className="mt-3 text-2xl font-semibold">AI7Lab builds {productName}—so compare the evidence, not the claim.</h2><p className="mt-5 leading-7 text-muted-foreground">This article is published by AI7Lab, the company behind {productName}. Evaluate the approach against explicit criteria: outcome quality, regional fit, integration effort, controls, portability, operating cost, and supplier support. {taedArticle ? 'Traditional OCR may be more suitable for stable, text-only templates; a generic model may suit low-risk experimentation; an internal build can make sense when the workflow is strategic and the team can own it for years.' : vendorEyeArticle ? 'Email or spreadsheets may remain sufficient for a small, low-risk supplier base; an ERP vendor master may be enough for finance records; a major procurement suite can be more appropriate for broad global source-to-pay transformation.' : 'A third-party platform may be preferable when speed and standardization matter more than differentiation; proprietary investment is justified only where owned data, workflow, evaluation, or distribution creates durable advantage.'}</p><a href={productHref} {...(productHref.startsWith('http') ? { target: '_blank', rel: 'noreferrer' } : {})} className="mt-7 inline-flex items-center gap-2 rounded-full bg-foreground px-5 py-3 text-sm font-medium text-background">{productAction}<ExternalLink className="h-4 w-4" /></a></section>}
        <section className="mt-16"><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">AI7Lab perspective</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">A practical 90-day path to evidence</h2><ol className="mt-8 border-l border-primary/25">{[['Days 1–30 · Frame','Select one commercially meaningful workflow. Establish baseline performance, data classification, owners, failure policy, and an evaluation set.'],['Days 31–60 · Prove','Build the thinnest end-to-end path inside real permissions and integrations. Test normal, difficult, malicious, and Arabic/English cases.'],['Days 61–90 · Operate','Release to a controlled cohort. Observe outcome quality, adoption, latency, exceptions, security signals, and cost; then make the scale, revise, or stop decision.']].map(([title,copy],i) => <li key={title} className="relative pb-8 pl-8"><span className="absolute -left-4 top-0 flex h-8 w-8 items-center justify-center rounded-full border border-primary/30 bg-background font-mono text-xs text-primary">0{i+1}</span><h3 className="font-semibold">{title}</h3><p className="mt-2 leading-7 text-muted-foreground">{copy}</p></li>)}</ol></section>
        <section className="mt-16"><h2 className="text-3xl font-semibold tracking-tight">Research and standards</h2><p className="mt-4 leading-7 text-muted-foreground">This article is strategic and technical guidance, not legal advice. Confirm current requirements with qualified UAE counsel and the relevant regulator.</p><ul className="mt-6 divide-y divide-border border-y border-border">{sources.map((source) => <li key={source.url} className="py-4"><a href={source.url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-4 font-medium hover:text-primary"><span>{source.title} <span className="font-normal text-muted-foreground">— {source.publisher}</span></span><ExternalLink className="h-4 w-4 shrink-0" /></a></li>)}</ul></section>
        <section className="mt-16 border-t border-border pt-10"><p className="text-sm font-medium text-primary">Share-ready takeaway</p><blockquote className="mt-3 text-2xl font-semibold leading-snug">“{shareTakeaway(article)}”</blockquote></section>
      </article>
      <aside className="border-t border-border bg-card/50"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><h2 className="text-3xl font-semibold">Continue this research pillar</h2><Link href={`/insights#pillar-${article.pillar}`} className="text-sm font-medium text-primary">View all pillar articles</Link></div><div className="mt-8 grid gap-5 md:grid-cols-3">{related.map((item) => <Link key={item.slug} href={`/insights/research/${item.slug}`} className="group rounded-2xl border border-border bg-background p-6 hover:border-primary/30"><span className="font-mono text-xs text-primary">Research {String(item.number).padStart(3,'0')}</span><h3 className="mt-3 font-semibold leading-snug">{item.title}</h3><span className="mt-5 inline-flex items-center gap-2 text-sm text-primary">Read article <ArrowRight className="h-4 w-4 group-hover:translate-x-1" /></span></Link>)}</div></div></aside>
    </main>
  </>
}
